# Generated by Django 2.0.7 on 2018-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('connections', models.ManyToManyField(related_name='_user_connections_+', to='connection_app.User')),
            ],
        ),
    ]
